### ISSUE TITLE
Not able to run Extractocol: src/extractocol/tester/Extractocol.java giving compilation error

### ISSUE THREAD

**Issue by mukulika-maity** [kaist-ina/Extractocol_public#17]
It is said to run Extractocol by running src/extractocol/tester/Extractocol.java with your application name as an argument.
But, this file itself does not compile. It gives the following error
_
src/extractocol/src/extractocol/tester/Extractocol.java:3: error: cannot find symbol
import extractocol.Constants;
                  ^
  symbol:   class Constants
  location: package extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:4: error: package extractocol.backend.response.helper does not exist
import extractocol.backend.response.helper.BlockTravelerHelper;
                                          ^
src/extractocol/src/extractocol/tester/Extractocol.java:5: error: package extractocol.common.helper does not exist
import extractocol.common.helper.MultiThreadHelper;
                                ^
src/extractocol/src/extractocol/tester/Extractocol.java:6: error: package extractocol.common.outputs.helper does not exist
import extractocol.common.outputs.helper.StdOutputController;
                                        ^
src/extractocol/src/extractocol/tester/Extractocol.java:7: error: package extractocol.common.trackers does not exist
import extractocol.common.trackers.ImplicitCallEdgeTracker;
                                  ^
src/extractocol/src/extractocol/tester/Extractocol.java:8: error: package extractocol.common.trackers does not exist
import extractocol.common.trackers.IntentMapTracker;
                                  ^
src/extractocol/src/extractocol/tester/Extractocol.java:9: error: package extractocol.frontend.basic does not exist
import extractocol.frontend.basic.ExtractocolLogger;
                                 ^
src/extractocol/src/extractocol/tester/Extractocol.java:10: error: package extractocol.frontend.helper does not exist
import extractocol.frontend.helper.PropagateHelper;
                                  ^
src/extractocol/src/extractocol/tester/Extractocol.java:11: error: package extractocol.frontend.output.basic does not exist
import extractocol.frontend.output.basic.TaintResultEntry;
                                        ^
src/extractocol/src/extractocol/tester/Extractocol.java:37: error: cannot find symbol
		if(Constants.getIsRetrofit())
		   ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:53: error: cannot find symbol
		ExtractocolLogger.Log("Extractocol Total Elapsed Time: " + secondToHMS(totTime));
		^
  symbol:   variable ExtractocolLogger
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:67: error: cannot find symbol
		if(!debug) StdOutputController.stop();
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:68: error: cannot find symbol
		ImplicitCallEdgeTracker.M(debug);
		^
  symbol:   variable ImplicitCallEdgeTracker
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:69: error: cannot find symbol
		if(!debug) StdOutputController.start();
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:72: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:85: error: cannot find symbol
		RetrofitAnalyzer.main(getRetrofitArg());
		^
  symbol:   variable RetrofitAnalyzer
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:89: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:102: error: cannot find symbol
		IntentMapTracker.M(debug);
		^
  symbol:   variable IntentMapTracker
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:106: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:118: error: cannot find symbol
		if(!debug) StdOutputController.stop(); 
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:119: error: cannot find symbol
		Frontend.main(getFrontendArg());
		^
  symbol:   variable Frontend
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:120: error: cannot find symbol
		if(!debug) StdOutputController.start();
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:123: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:135: error: cannot find symbol
		if(!debug) StdOutputController.stop();
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:136: error: cannot find symbol
		Backend.main(getBackendArg());
		^
  symbol:   variable Backend
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:137: error: cannot find symbol
		if(!debug) StdOutputController.start();
		           ^
  symbol:   variable StdOutputController
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:140: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:153: error: cannot find symbol
		HeapHandling.main(getHeapHandlingArg());
		^
  symbol:   variable HeapHandling
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:157: error: cannot find symbol
		BlockTravelerHelper.SerializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:167: error: cannot find symbol
	private static String[] getRetrofitArg() { return splitter(Constants.getAPPName() + (debug? " --debug" : ""));	}
	                                                           ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:168: error: cannot find symbol
	private static String[] getFrontendArg() { return splitter(Constants.getAPPName()); }
	                                                           ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:169: error: cannot find symbol
	private static String[] getBackendArg() { return splitter("--app " + Constants.getAPPName()); }
	                                                                     ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:170: error: cannot find symbol
	private static String[] getHeapHandlingArg() { return splitter("--app " + Constants.getAPPName()); }
	                                                                          ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:197: error: cannot find symbol
		ExtractocolLogger.Log("Extractocol is running... (App Name: " + Constants.getAPPName() + ", # Processors: " + MultiThreadHelper.getCoreNum() + ")\n");
		                                                                ^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:197: error: cannot find symbol
		ExtractocolLogger.Log("Extractocol is running... (App Name: " + Constants.getAPPName() + ", # Processors: " + MultiThreadHelper.getCoreNum() + ")\n");
		                                                                                                              ^
  symbol:   variable MultiThreadHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:197: error: cannot find symbol
		ExtractocolLogger.Log("Extractocol is running... (App Name: " + Constants.getAPPName() + ", # Processors: " + MultiThreadHelper.getCoreNum() + ")\n");
		^
  symbol:   variable ExtractocolLogger
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:198: error: cannot find symbol
		Constants.setIsFullStack(true);
		^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:199: error: cannot find symbol
		BlockTravelerHelper.DeserializeBackEdge();
		^
  symbol:   variable BlockTravelerHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:203: error: cannot find symbol
		Constants.setAPPName(args[0]);
		^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:211: error: cannot find symbol
				PropagateHelper.setMaxMainStream(Integer.parseInt(args[k + 1]));
				^
  symbol:   variable PropagateHelper
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:219: error: cannot find symbol
				TaintResultEntry.setMaxDepth(Integer.parseInt(args[k + 1]));
				^
  symbol:   variable TaintResultEntry
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:227: error: cannot find symbol
				Constants.setIsRetrofit(true);
				^
  symbol:   variable Constants
  location: class Extractocol
src/extractocol/src/extractocol/tester/Extractocol.java:251: error: cannot find symbol
				Frontend.setStride(Integer.parseInt(args[k + 1]));
				^
  symbol:   variable Frontend
  location: class Extractocol
43 errors
![Screen Shot 2021-07-02 at 10 23 36 AM](https://user-images.githubusercontent.com/32633827/124223642-b90d6a80-db21-11eb-8ce1-d5d17e0bd241.png)

**Comment by appff** [comment]
To easily solve this problem, try to use IDEA (intellij) which automatically sets up build path.
and if you use IDEA to execute Extractocol without any project options, you should encounter junit lib error in soot-infoflow project.
Must exclude test, and securiBench folder in soot-infoflow project. (Open the module setting)
